# Generated by Django 4.1.6 on 2023-02-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_img', models.ImageField(upload_to='media')),
                ('prod_name', models.CharField(max_length=120)),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('prod_desc', models.TextField()),
            ],
        ),
    ]
