# Generated by Django 4.1.6 on 2023-02-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_cart_prod_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('user_add', models.TextField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_mob', models.IntegerField(default=None)),
                ('user_city', models.CharField(max_length=250)),
                ('user_state', models.CharField(max_length=250)),
                ('user_pincode', models.IntegerField(default=None)),
            ],
        ),
    ]
