# Generated by Django 4.1.6 on 2023-02-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_mob',
            field=models.BigIntegerField(default=None),
        ),
    ]
