# Generated by Django 4.1.6 on 2023-02-21 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_alter_user_user_mob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=None)),
                ('price', models.IntegerField()),
                ('prodId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.product')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.user')),
            ],
        ),
    ]
