# Generated by Django 4.1.6 on 2023-02-21 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_order_address_order_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prodId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
        migrations.AddField(
            model_name='order',
            name='cartId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shopping.cart'),
        ),
    ]
