# Generated by Django 4.1.6 on 2023-02-21 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_remove_order_price_remove_order_prodid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='prodId',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='prod_qty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cartId',
        ),
        migrations.AddField(
            model_name='cart',
            name='userId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shopping.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=None),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=None)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.order')),
                ('prodId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=None)),
                ('cartId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.cart')),
                ('prodId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.product')),
            ],
        ),
    ]
