# Generated by Django 4.1.6 on 2023-02-22 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_alter_orderitems_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.order'),
        ),
    ]
